-- CUSA ESPN Compliance Dashboard — Initial School Data
-- Run AFTER schema.sql. Safe to re-run (uses ON CONFLICT DO NOTHING).

insert into schools (
  name, conference, auth_email, sports,
  sw_model, sw_inputs, sw_keyers, sw_mes,
  cameras, camera_models,
  cam_football, cam_basketball, cam_volleyball, cam_soccer, cam_baseball, cam_softball,
  has_40x_lens, lens_detail, has_14x_lens,
  replay_model, replay_units, replay_inputs, replay_outputs,
  audio_model, audio_inputs, audio_outputs, audio_faders,
  intercom_model, intercom_ch,
  gfx_model, gfx_channels, gfx_approved,
  tx_digital, tx_approved, backup_power,
  mv_sources, mv_software
) values
(
  'Western Kentucky','CUSA','jordan.basham@wku.edu',
  ARRAY['Baseball','Basketball','Football','Soccer','Softball','Volleyball'],
  'Grass Valley Kayenne',48,4,2.5,
  6,'6 Ikegami HDK-77EC',
  0,0,0,0,0,0,
  true,'Fujinon XA 50x9.5 (2)',true,
  'NewTek 3Play / Vizrt 3Play',2,4,2,
  'Yamaha M7CL',48,32,62,
  'RTS Telex',8,
  'Ross XPression + AJT Livebook',3,true,
  'Haivision IP Encoder',true,false,
  8,'Evertz Magnum'
),
(
  'Sam Houston','CUSA','JDB014@shsu.edu',
  ARRAY['Baseball','Basketball','Football','Soccer','Softball','Volleyball'],
  'Ross Carbonite',24,4,2,
  6,'6 Hitachi 5550',
  0,0,0,0,0,0,
  false,'Max 26x (Fujinon Box Lens 26x)',true,
  '3Play 4800 / 3Play 440',2,8,2,
  'Beringer X32',32,16,24,
  'Clear Com',4,
  'Ross Xpression + XPN Go',4,true,
  'Haivision IP Encoder',true,true,
  24,'Ross'
),
(
  'New Mexico State','CUSA','vconway@nmsu.edu',
  ARRAY['Baseball','Basketball','Football','Softball','Volleyball'],
  'Ross Carbonite Ultra CUF-124',24,4,2,
  13,'6 Sony HSC 100R + 3 Marshall CV506 + others',
  0,0,0,0,0,0,
  true,'Canon XJ60X9BIE (2)',true,
  'EVS XT-VIA',1,6,2,
  'Yamaha DM7',32,16,28,
  'RTS Odin 32',32,
  'Ross Xpression 3ch',3,true,
  'Haivision IP Encoder',true,false,
  24,'Ross Dashboard'
),
(
  'MTSU','CUSA','nathan.wallach@mtsu.edu',
  ARRAY['Baseball','Basketball','Football','Soccer','Softball','Volleyball'],
  'Carbonite Ultra CUF-124',24,2,2.5,
  5,'5 Panasonic AK-HC3900GSJ',
  0,0,0,0,0,0,
  true,'Canon XJ80x8.8B (1)',true,
  'Ross Mira+',1,8,8,
  'Yamaha DM7-EX',120,120,32,
  'Clear Com Free Speak',0,
  'XPression XST3',3,true,
  'Haivision IP Encoder',true,true,
  16,'Ross'
),
(
  'Missouri State','MVC','brandon@hite-media.com',
  ARRAY['Baseball','Basketball','Football','Soccer','Softball','Swimming','Volleyball'],
  'Ross Carbonite Multi Media',16,4,2,
  4,'4 HXC FB80',
  0,0,0,0,0,0,
  true,'Canon Super 55, Fujinon 42X',true,
  'Newtek 3 Play',1,4,2,
  'Behringer X32',32,16,32,
  'Clear Com PL',1,
  'Ross Xpression SCE',1,true,
  'Haivision IP Encoder',true,false,
  16,'Built in to Switcher'
),
(
  'Liberty','CUSA','rfkeating@liberty.edu',
  ARRAY['Baseball','Basketball','Field Hockey','Football','Ice Hockey','Lacrosse','Soccer','Softball','Swimming','Tennis','Track','Volleyball'],
  'GV Kayenne K-Frame XP',72,6,4,
  20,'12+ Sony HXC-FB80 (x20 total)',
  0,0,0,0,0,0,
  true,'Fujinon UA107X8.4 (2), UA70X8.7 (7)',true,
  'DreamCatcher',1,12,12,
  'Calrec Artemis+',256,512,64,
  'Riedel Artist 1024',1024,
  'XPression (x6 centralized)',8,true,
  'Haivision IP Encoder',true,true,
  96,'Evertz EV 670/3067'
),
(
  'Jacksonville State','CUSA','klflippo@jsu.edu',
  ARRAY['Baseball','Basketball','Football','Soccer','Softball','Volleyball'],
  'NewTek Tricaster TC1',16,4,4,
  6,'4 JVC GY-HC500U + 2 JVC GY-HM620U',
  0,0,0,0,0,0,
  false,'Max 23x (Fujinon Zoom 23x)',true,
  'NewTek 3Play 3P1',1,4,1,
  'Mackie 1402-VLZ4',14,7,10,
  'Clear-Com Encore MS702',8,
  'Ross Xpression 10.5 + AJT',2,true,
  'Haivision IP Encoder',true,false,
  8,'Tricaster'
),
(
  'FIU','CUSA','ngarrido@fiu.edu',
  ARRAY['Baseball','Basketball','Football','Soccer','Softball','Volleyball'],
  'NewTek TC1',16,2,2,
  5,'5 SONY PXW',
  0,0,0,0,0,0,
  false,'Lenses listed as N/A',false,
  'NewTek 3Play',1,4,4,
  'Allen & Heath AH-SQ-6',48,48,24,
  'Hollyland Solidcom M1',8,
  'AJT Livebook (x2)',4,true,
  'Haivision IP Encoder',true,false,
  8,'TC1'
),
(
  'Delaware','CUSA','pfleiger@udel.edu',
  ARRAY['Baseball','Basketball','Field Hockey','Football','Lacrosse','Soccer','Softball','Volleyball'],
  'Ross Carbonite + TC1 Tri Casters',24,4,2,
  11,'5 Hitachi SK HD1000 + 6 JVC Gy-HM180U',
  0,0,0,0,0,0,
  true,'Fujinon Digipower 50 (3)',true,
  'Ross Mira + 3Play 3P1 (x2)',3,4,2,
  'Soundcraft EPM12',12,2,12,
  'Clear-Com Free Speak II',12,
  'Ross Xpression + AJT LiveBook',7,true,
  'Not specified',false,true,
  16,'Ross Carbonite'
),
(
  'Kennesaw State','CUSA','Nalexa29@kennesaw.edu',
  ARRAY['Baseball','Basketball','Football','Lacrosse','Soccer','Softball','Volleyball'],
  'Ross Carbonite (x2)',24,4,2,
  8,'4 Panasonic HPX-370 + 4 Panasonic CX-350',
  0,0,0,0,0,0,
  false,'Max 18-20x (Panasonic 18x)',true,
  'Ross Mira Replay',4,9,3,
  'Behringer X32',16,16,16,
  'ClearComm',0,
  'Ross Xpression (x3)',3,true,
  'Haivision IP Encoder',true,true,
  0,'n/a'
)
on conflict (name) do nothing;
